name: Scheduled Jobs

on:
  schedule:
    # Every Tuesday at 4:00 AM EST (8:00 UTC)
    - cron: "0 8 * * 2"
    # Every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  refresh:
    if: github.event.schedule == '0 8 * * 2'
    runs-on: ubuntu-latest
    steps:
      - name: Call refresh endpoint
        run: |
          curl -s -X POST "https://fantasy-power-rankings-backend.onrender.com/refresh"

  keep_warm:
    if: github.event.schedule == '*/15 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Call main site
        run: |
          curl -s -X GET "https://fantasy-power-rankings-backend.onrender.com/power-rankings"
